apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: routepatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: routepatcher
subjects:
- kind: ServiceAccount
  name: routepatcher

