apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: preview1
  name: routepatcher
rules:
- apiGroups: ["networking.istio.io"] # "" indicates the core API group
  resources: ["virtualservices", "destinationrules"]
  verbs: ["get", "watch", "list", "patch", "update"]
